---
title: "Final project"
author: "Ruining Zheng & Yixuan Li"
format: html
editor: visual
self-contained: true
---

```{r message=FALSE}
library(tidyverse)
library(readxl)
library(tigris)
library(tidycensus)
library(ggplot2)
library(tigris)
library(sf)
library(dotenv)
library(here)
library(utils)
library(lubridate)
library(janitor)
library(zipcodeR)
```

```{r}
load_dot_env(here("C:/Users/Ruining Zheng/Desktop/GU/PPOL 670 Intro to Data Science/Final/Final_project/", ".env"))
credential <- Sys.getenv("station_api_key")
url <- str_glue("https://developer.nrel.gov/api/alt-fuel-stations/v1.csv?api_key={credential}&format=csv")

station_data <- read.csv(url) %>%
  janitor::clean_names() %>%
  select(- plus4)

charging_station <- station_data %>%
  select(station_name, city, state, zip, latitude, longitude)
  
```

```{r}
ny_ev <- read_csv("data/ny_ev_registrations.csv", col_types = c("ZIP Code" = "character")) %>%
  janitor::clean_names() %>%
  mutate(year = year(registration_valid_date)) %>%
  filter(year <= 2021) %>%
  group_by(zip_code) %>%
  filter(zip_code < 14925) %>%
  count()
```

```{r, message=FALSE}
census_data <- get_acs(geography = "county",
                        year = 2021,
                        variable = as.character(c("B01003_001E", "B19001_001E", "B08006_002E"),
                         geometry = TRUE
                         )) %>%
  janitor::clean_names() %>%
  select(-moe) %>%
  separate(name, into = c("county", "state"), sep = ",")
                          
geoid_location <- st_read("data/tl_2022_us_zcta520/tl_2022_us_zcta520.shp") %>%
  janitor::clean_names() %>%
  rename(geoid = geoid20) %>%
  select(geoid, geometry)

census_geometry <- left_join(x = census_data, y = geoid_location, by = "geoid") %>%
  drop_na()
  
```

```{r, warning=FALSE}
air_quality <- read_excel("data/PM2.5.xlsx", skip = 2) %>%
  janitor::clean_names() %>%
  select(core_based_statistical_area_cbsa, x2010_population, pm2_5_wtd_am_mg_m3) %>%
  rename(pm2_5 = pm2_5_wtd_am_mg_m3) %>%
  filter(pm2_5 != "ND", pm2_5 != "IN")
```

```{r}

```
